### ISSUE TITLE
2017-07-28 | Clojure/conj 2017

### ISSUE THREAD

**Issue by lynngrogan** [catehstn/technically-speaking#437] opened 2017-06-27 16:11 UTC
If you are submitting a CFP:
----------------------------
We require conferences to have code of conduct, and highly prefer those they pays travel expenses / speaker fee to speakers.

The title of the issue should be the CFP deadline, then the title of the conference e.g. 2016-04-29: 360|AnDev

### Clojure/conj 2017
*Celebrating 10 years of the Clojure programming language* 
 
Event date: October 12-14, 2017
Location: Baltimore, MD
Submission deadline: Friday, July 28
Travel expenses covered: Conference ticket, 4 nights lodging, $550 USD travel reimbursement
[conf link](2017.clojure-conj.org)
[cfp](http://2017.clojure-conj.org/cfp/)
[@clojure_conj](https://twitter.com/Clojure_conj)

If you are submitting a link, please include:
---------------------------------------------
URL
Author name
Author twitter handle (if available)
Your twitter handle (optional)
Short description of what you loved about it

Submit your own content, your friends', or something you saw on the internet. Do not self-censor. Do not try to decide if it is "worthy" or not. Just submit!

**Comment by chiuki** [comment] 2017-06-27 16:38
Duplicate of #420

**Closed by chiuki** 2017-06-27 16:38 UTC
