### ISSUE TITLE
2017-11-14|The Lead Developer Austin

### ISSUE THREAD

**Issue by whiteoctevents** [catehstn/technically-speaking#562] opened 2017-10-31 11:43 UTC
### The Lead Developer Austin 2018
*The conference for tech leads*
 
Event date: 2 March 2018
Location: Austin, Texas
Submission deadline: 14 November 2017
Travel expenses covered: Yes
[austin2018.theleaddeveloper.com](http://wvnts.co/2gYVp3M)
[The Lead Developer Austin CFP guidance and application](http://wvnts.co/2gPI89P)
[@theleaddev](http://wvnts.co/2z5szW2)

**Comment by chiuki** [comment] 2017-10-31 21:01
Duplicate of #558

**Closed by chiuki** 2017-10-31 21:01 UTC
Labels: Duplicate
