### ISSUE TITLE
20 March 2018: PIPELINE

### ISSUE THREAD

**Issue by camilleacey** [catehstn/technically-speaking#556] opened 2017-10-18 15:27 UTC
### PIPELINE
*PIPELINE is a one-day not-for-profit conference focused on Continuous Delivery run by practitioners for practitioners. @PipelineConf*

Event date: 20 March 2018
Location: Victoria, London - UK
Submission deadline:  5 December 2017
Travel expenses covered: YES
[Website](https://web.pipelineconf.info/)
[CFP](https://web.pipelineconf.info/submit-a-proposal/)
[@PipelineConf](https://twitter.com/PipelineConf)

**Comment by chiuki** [comment] 2017-10-18 15:30
Duplicate of #554

**Closed by chiuki** 2017-10-18 15:30 UTC
Labels: CFP, Duplicate
