### ISSUE TITLE
Blog post about tech talk preparation process

### ISSUE THREAD

**Issue by zmdominguez** [catehstn/technically-speaking#359] opened 2017-04-18 01:19 UTC
URL: http://zdominguez.com/2017/04/17/all-it-takes-patience.html
Author name: Zarah Dominguez
Author twitter handle (if available): @zarahjutz
Your twitter handle (optional): @zarahjutz
Short description of what you loved about it: Cause I wrote it? Kidding! I hope that this post will help people realise that it takes a lot of effort to make something look effortless.

**Comment by catehstn** [comment] 2017-04-30 14:45
Duplicate of #370 (will be included in #375 )

**Closed by catehstn** 2017-04-30 14:45 UTC
Labels: Link
