### ISSUE TITLE
How to Write a Lightning Talk

### ISSUE THREAD

**Issue by stellacotton** [catehstn/technically-speaking#291] opened 2017-02-16 22:46 UTC
Wish I'd had this when writing my first lightning talk! Writing even a short talk can feel really daunting and the advice here was so practical and action-oriented. (h/t @math_rachel for tweeting this out)

http://www.heidiwaterhouse.com/2016/06/19/how-to-write-a-lightning-talk/
Heidi Waterhouse
@wiredferret

**Comment by catehstn** [comment] 2017-02-21 08:26
This was included in #59 ! Duplicate of #48 :) thank you though!

**Closed by catehstn** 2017-02-21 08:26 UTC
