### ISSUE TITLE
2017-10-01: Elixir with Love

### ISSUE THREAD

**Issue by rserur** [catehstn/technically-speaking#493] opened 2017-08-02 01:45 UTC
### Elixir with Love
*An Elixir programming language conference driven by inclusion. (accepting technical & cultural talks)*

Event date: November 10th, 2017
Location: Providence, RI
Submission deadline: October 1st (rolling CFP)
Travel expenses covered: yes
[elixir-with-love.com](http://www.elixir-with-love.com)
[papercall.io/elixirwithlove](https://www.papercall.io/elixirwithlove)
[@elixir_w_love](https://twitter.com/elixir_w_love)

**Comment by chiuki** [comment] 2017-08-02 02:00
Duplicate of #387. Included in https://tinyletter.com/techspeak/letters/technically-speaking-june-27-2017

**Closed by chiuki** 2017-08-02 02:00 UTC
